#ifndef COLORS_H
#define COLORS_H

//foreground colors
#define TEXT_COLOR COLOR_BLACK
#define SUIT1_COLOR COLOR_BLACK
#define SUIT2_COLOR COLOR_RED
#define SUIT3_COLOR COLOR_BLACK
#define SUIT4_COLOR COLOR_RED

//background colors
#define BACKGROUND_COLOR COLOR_GREEN
#define EMPTY_PILE_COLOR COLOR_GREEN
#define CARD_NORMAL_COLOR COLOR_WHITE
#define CARD_CURSOR_COLOR COLOR_BLUE
#define CARD_SELECTED_COLOR COLOR_YELLOW

//background numbers
//used for printcolor cardBackground argument
#define CARD_EMPTY 20
#define CARD_NORMAL 30
#define CARD_CURSOR 40
#define CARD_SELECTED 50

//color pairs
#define BACKGROUND 10
#define EMPTY_PILE 20
#define NORMAL_TEXT 30
#define NORMAL_SUIT1 31
#define NORMAL_SUIT2 32
#define NORMAL_SUIT3 33
#define NORMAL_SUIT4 34
#define CURSOR_TEXT 40
#define CURSOR_SUIT1 41
#define CURSOR_SUIT2 42
#define CURSOR_SUIT3 43
#define CURSOR_SUIT4 44
#define SELECTED_TEXT 50
#define SELECTED_SUIT1 51
#define SELECTED_SUIT2 52
#define SELECTED_SUIT3 53
#define SELECTED_SUIT4 54

//creates the color pairs accordingly
void CreateColorPairs()
{
    init_pair(BACKGROUND, TEXT_COLOR, BACKGROUND_COLOR);
    init_pair(EMPTY_PILE, TEXT_COLOR, BACKGROUND_COLOR);

    init_pair(NORMAL_TEXT, TEXT_COLOR, CARD_NORMAL_COLOR);
    init_pair(NORMAL_SUIT1, SUIT1_COLOR, CARD_NORMAL_COLOR);
    init_pair(NORMAL_SUIT2, SUIT2_COLOR, CARD_NORMAL_COLOR);
    init_pair(NORMAL_SUIT3, SUIT3_COLOR, CARD_NORMAL_COLOR);
    init_pair(NORMAL_SUIT4, SUIT4_COLOR, CARD_NORMAL_COLOR);

    init_pair(CURSOR_TEXT, TEXT_COLOR, CARD_CURSOR_COLOR);
    init_pair(CURSOR_SUIT1, SUIT1_COLOR, CARD_CURSOR_COLOR);
    init_pair(CURSOR_SUIT2, SUIT2_COLOR, CARD_CURSOR_COLOR);
    init_pair(CURSOR_SUIT3, SUIT3_COLOR, CARD_CURSOR_COLOR);
    init_pair(CURSOR_SUIT4, SUIT4_COLOR, CARD_CURSOR_COLOR);

    init_pair(SELECTED_TEXT, TEXT_COLOR, CARD_SELECTED_COLOR);
    init_pair(SELECTED_SUIT1, SUIT1_COLOR, CARD_SELECTED_COLOR);
    init_pair(SELECTED_SUIT2, SUIT2_COLOR, CARD_SELECTED_COLOR);
    init_pair(SELECTED_SUIT3, SUIT3_COLOR, CARD_SELECTED_COLOR);
    init_pair(SELECTED_SUIT4, SUIT4_COLOR, CARD_SELECTED_COLOR);
}

#endif